name: Deploy
"on":
  workflow_dispatch:
concurrency: ${{ github.event.repository.name }}
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub
          aws-region: ${{ secrets.AWS_REGION }}
      - id: log-in-to-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.log-in-to-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - run: |
          sam deploy \
            --stack-name=${{ github.event.repository.name }} \
            --parameter-overrides \
              DiscordBotToken=${{ secrets.DISCORD_BOT_TOKEN }} \
              DiscordBotImageUri=${{ steps.log-in-to-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPOSITORY_NAME }}:${{ github.sha }}
